# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xe7XWeG1j32fXYk-EZcUqP8l4s_4Kh5Z
"""

# Задача 2.1. 

# Создайте две функции maximum и minimum,
# которые получают список целых чисел в качестве входных данных 
# и возвращают наибольшее и наименьшее число в этом списке соответственно.
# Например,
# * [4,6,2,1,9,63,-134,566]         -> max = 566, min = -134
# * [-52, 56, 30, 29, -54, 0, -110] -> min = -110, max = 56
# * [42, 54, 65, 87, 0]             -> min = 0, max = 87
# * [5]                             -> min = 5, max = 5
# функции sorted, max и min использовать нельзя!

def minimum(arr):
  for i in range(len(arr)):
    if i < len(arr) - 1:
      x = i
      y = i + 1
      while y < len(arr):
        if arr[y] < arr[x]:
          x = y
        y += 1
      arr[i],arr[x] = arr[x],arr[i]
      i += 1
  mini = arr[0]
  return mini

def maximum(arr):
  for i in range(len(arr)):
    if i < len(arr) - 1:
      x = i
      y = i + 1
      while y < len(arr):
        if arr[y] < arr[x]:
          x = y
        y += 1
      arr[i],arr[x] = arr[x],arr[i]
      i += 1
  maxi = arr[i]
  return maxi

int_list = input('Введите числа через пробел').split()
min_int = minimum(int_list)
max_int = maximum(int_list)

print('max =', max_int,', min =', min_int)